// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_2eproto;
namespace osr {
class ClientMessage;
struct ClientMessageDefaultTypeInternal;
extern ClientMessageDefaultTypeInternal _ClientMessage_default_instance_;
class GachaPullRequest;
struct GachaPullRequestDefaultTypeInternal;
extern GachaPullRequestDefaultTypeInternal _GachaPullRequest_default_instance_;
class GameActionRequest;
struct GameActionRequestDefaultTypeInternal;
extern GameActionRequestDefaultTypeInternal _GameActionRequest_default_instance_;
class LoginRequest;
struct LoginRequestDefaultTypeInternal;
extern LoginRequestDefaultTypeInternal _LoginRequest_default_instance_;
class ServerResponse;
struct ServerResponseDefaultTypeInternal;
extern ServerResponseDefaultTypeInternal _ServerResponse_default_instance_;
}  // namespace osr
PROTOBUF_NAMESPACE_OPEN
template<> ::osr::ClientMessage* Arena::CreateMaybeMessage<::osr::ClientMessage>(Arena*);
template<> ::osr::GachaPullRequest* Arena::CreateMaybeMessage<::osr::GachaPullRequest>(Arena*);
template<> ::osr::GameActionRequest* Arena::CreateMaybeMessage<::osr::GameActionRequest>(Arena*);
template<> ::osr::LoginRequest* Arena::CreateMaybeMessage<::osr::LoginRequest>(Arena*);
template<> ::osr::ServerResponse* Arena::CreateMaybeMessage<::osr::ServerResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace osr {

enum MessageType : int {
  LOGIN = 0,
  GACHA_PULL = 1,
  GAME_ACTION = 2,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = LOGIN;
constexpr MessageType MessageType_MAX = GAME_ACTION;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class LoginRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osr.LoginRequest) */ {
 public:
  inline LoginRequest() : LoginRequest(nullptr) {}
  ~LoginRequest() override;
  explicit PROTOBUF_CONSTEXPR LoginRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginRequest(const LoginRequest& from);
  LoginRequest(LoginRequest&& from) noexcept
    : LoginRequest() {
    *this = ::std::move(from);
  }

  inline LoginRequest& operator=(const LoginRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginRequest& operator=(LoginRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginRequest* internal_default_instance() {
    return reinterpret_cast<const LoginRequest*>(
               &_LoginRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LoginRequest& a, LoginRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginRequest& from) {
    LoginRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osr.LoginRequest";
  }
  protected:
  explicit LoginRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:osr.LoginRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class GachaPullRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osr.GachaPullRequest) */ {
 public:
  inline GachaPullRequest() : GachaPullRequest(nullptr) {}
  ~GachaPullRequest() override;
  explicit PROTOBUF_CONSTEXPR GachaPullRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GachaPullRequest(const GachaPullRequest& from);
  GachaPullRequest(GachaPullRequest&& from) noexcept
    : GachaPullRequest() {
    *this = ::std::move(from);
  }

  inline GachaPullRequest& operator=(const GachaPullRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GachaPullRequest& operator=(GachaPullRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GachaPullRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GachaPullRequest* internal_default_instance() {
    return reinterpret_cast<const GachaPullRequest*>(
               &_GachaPullRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GachaPullRequest& a, GachaPullRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GachaPullRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GachaPullRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GachaPullRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GachaPullRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GachaPullRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GachaPullRequest& from) {
    GachaPullRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GachaPullRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osr.GachaPullRequest";
  }
  protected:
  explicit GachaPullRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
    kPullCountFieldNumber = 2,
  };
  // int32 user_id = 1;
  void clear_user_id();
  int32_t user_id() const;
  void set_user_id(int32_t value);
  private:
  int32_t _internal_user_id() const;
  void _internal_set_user_id(int32_t value);
  public:

  // int32 pull_count = 2;
  void clear_pull_count();
  int32_t pull_count() const;
  void set_pull_count(int32_t value);
  private:
  int32_t _internal_pull_count() const;
  void _internal_set_pull_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:osr.GachaPullRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t user_id_;
    int32_t pull_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class GameActionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osr.GameActionRequest) */ {
 public:
  inline GameActionRequest() : GameActionRequest(nullptr) {}
  ~GameActionRequest() override;
  explicit PROTOBUF_CONSTEXPR GameActionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameActionRequest(const GameActionRequest& from);
  GameActionRequest(GameActionRequest&& from) noexcept
    : GameActionRequest() {
    *this = ::std::move(from);
  }

  inline GameActionRequest& operator=(const GameActionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameActionRequest& operator=(GameActionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameActionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameActionRequest* internal_default_instance() {
    return reinterpret_cast<const GameActionRequest*>(
               &_GameActionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GameActionRequest& a, GameActionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GameActionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameActionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameActionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameActionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameActionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameActionRequest& from) {
    GameActionRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameActionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osr.GameActionRequest";
  }
  protected:
  explicit GameActionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
    kChoiceFieldNumber = 2,
    kScenarioIdFieldNumber = 3,
  };
  // int32 user_id = 1;
  void clear_user_id();
  int32_t user_id() const;
  void set_user_id(int32_t value);
  private:
  int32_t _internal_user_id() const;
  void _internal_set_user_id(int32_t value);
  public:

  // int32 choice = 2;
  void clear_choice();
  int32_t choice() const;
  void set_choice(int32_t value);
  private:
  int32_t _internal_choice() const;
  void _internal_set_choice(int32_t value);
  public:

  // int32 scenario_id = 3;
  void clear_scenario_id();
  int32_t scenario_id() const;
  void set_scenario_id(int32_t value);
  private:
  int32_t _internal_scenario_id() const;
  void _internal_set_scenario_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:osr.GameActionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t user_id_;
    int32_t choice_;
    int32_t scenario_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class ClientMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osr.ClientMessage) */ {
 public:
  inline ClientMessage() : ClientMessage(nullptr) {}
  ~ClientMessage() override;
  explicit PROTOBUF_CONSTEXPR ClientMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientMessage(const ClientMessage& from);
  ClientMessage(ClientMessage&& from) noexcept
    : ClientMessage() {
    *this = ::std::move(from);
  }

  inline ClientMessage& operator=(const ClientMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientMessage& operator=(ClientMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientMessage& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kLogin = 2,
    kGachaPull = 3,
    kGameAction = 4,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const ClientMessage* internal_default_instance() {
    return reinterpret_cast<const ClientMessage*>(
               &_ClientMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ClientMessage& a, ClientMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClientMessage& from) {
    ClientMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osr.ClientMessage";
  }
  protected:
  explicit ClientMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kLoginFieldNumber = 2,
    kGachaPullFieldNumber = 3,
    kGameActionFieldNumber = 4,
  };
  // .osr.MessageType type = 1;
  void clear_type();
  ::osr::MessageType type() const;
  void set_type(::osr::MessageType value);
  private:
  ::osr::MessageType _internal_type() const;
  void _internal_set_type(::osr::MessageType value);
  public:

  // .osr.LoginRequest login = 2;
  bool has_login() const;
  private:
  bool _internal_has_login() const;
  public:
  void clear_login();
  const ::osr::LoginRequest& login() const;
  PROTOBUF_NODISCARD ::osr::LoginRequest* release_login();
  ::osr::LoginRequest* mutable_login();
  void set_allocated_login(::osr::LoginRequest* login);
  private:
  const ::osr::LoginRequest& _internal_login() const;
  ::osr::LoginRequest* _internal_mutable_login();
  public:
  void unsafe_arena_set_allocated_login(
      ::osr::LoginRequest* login);
  ::osr::LoginRequest* unsafe_arena_release_login();

  // .osr.GachaPullRequest gacha_pull = 3;
  bool has_gacha_pull() const;
  private:
  bool _internal_has_gacha_pull() const;
  public:
  void clear_gacha_pull();
  const ::osr::GachaPullRequest& gacha_pull() const;
  PROTOBUF_NODISCARD ::osr::GachaPullRequest* release_gacha_pull();
  ::osr::GachaPullRequest* mutable_gacha_pull();
  void set_allocated_gacha_pull(::osr::GachaPullRequest* gacha_pull);
  private:
  const ::osr::GachaPullRequest& _internal_gacha_pull() const;
  ::osr::GachaPullRequest* _internal_mutable_gacha_pull();
  public:
  void unsafe_arena_set_allocated_gacha_pull(
      ::osr::GachaPullRequest* gacha_pull);
  ::osr::GachaPullRequest* unsafe_arena_release_gacha_pull();

  // .osr.GameActionRequest game_action = 4;
  bool has_game_action() const;
  private:
  bool _internal_has_game_action() const;
  public:
  void clear_game_action();
  const ::osr::GameActionRequest& game_action() const;
  PROTOBUF_NODISCARD ::osr::GameActionRequest* release_game_action();
  ::osr::GameActionRequest* mutable_game_action();
  void set_allocated_game_action(::osr::GameActionRequest* game_action);
  private:
  const ::osr::GameActionRequest& _internal_game_action() const;
  ::osr::GameActionRequest* _internal_mutable_game_action();
  public:
  void unsafe_arena_set_allocated_game_action(
      ::osr::GameActionRequest* game_action);
  ::osr::GameActionRequest* unsafe_arena_release_game_action();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:osr.ClientMessage)
 private:
  class _Internal;
  void set_has_login();
  void set_has_gacha_pull();
  void set_has_game_action();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int type_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::osr::LoginRequest* login_;
      ::osr::GachaPullRequest* gacha_pull_;
      ::osr::GameActionRequest* game_action_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class ServerResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osr.ServerResponse) */ {
 public:
  inline ServerResponse() : ServerResponse(nullptr) {}
  ~ServerResponse() override;
  explicit PROTOBUF_CONSTEXPR ServerResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerResponse(const ServerResponse& from);
  ServerResponse(ServerResponse&& from) noexcept
    : ServerResponse() {
    *this = ::std::move(from);
  }

  inline ServerResponse& operator=(const ServerResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerResponse& operator=(ServerResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerResponse* internal_default_instance() {
    return reinterpret_cast<const ServerResponse*>(
               &_ServerResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ServerResponse& a, ServerResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ServerResponse& from) {
    ServerResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osr.ServerResponse";
  }
  protected:
  explicit ServerResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
    kUserIdFieldNumber = 3,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // int32 user_id = 3;
  void clear_user_id();
  int32_t user_id() const;
  void set_user_id(int32_t value);
  private:
  int32_t _internal_user_id() const;
  void _internal_set_user_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:osr.ServerResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    bool success_;
    int32_t user_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoginRequest

// string username = 1;
inline void LoginRequest::clear_username() {
  _impl_.username_.ClearToEmpty();
}
inline const std::string& LoginRequest::username() const {
  // @@protoc_insertion_point(field_get:osr.LoginRequest.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRequest::set_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:osr.LoginRequest.username)
}
inline std::string* LoginRequest::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:osr.LoginRequest.username)
  return _s;
}
inline const std::string& LoginRequest::_internal_username() const {
  return _impl_.username_.Get();
}
inline void LoginRequest::_internal_set_username(const std::string& value) {
  
  _impl_.username_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequest::_internal_mutable_username() {
  
  return _impl_.username_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginRequest::release_username() {
  // @@protoc_insertion_point(field_release:osr.LoginRequest.username)
  return _impl_.username_.Release();
}
inline void LoginRequest::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  _impl_.username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:osr.LoginRequest.username)
}

// string password = 2;
inline void LoginRequest::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& LoginRequest::password() const {
  // @@protoc_insertion_point(field_get:osr.LoginRequest.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRequest::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:osr.LoginRequest.password)
}
inline std::string* LoginRequest::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:osr.LoginRequest.password)
  return _s;
}
inline const std::string& LoginRequest::_internal_password() const {
  return _impl_.password_.Get();
}
inline void LoginRequest::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRequest::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginRequest::release_password() {
  // @@protoc_insertion_point(field_release:osr.LoginRequest.password)
  return _impl_.password_.Release();
}
inline void LoginRequest::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:osr.LoginRequest.password)
}

// -------------------------------------------------------------------

// GachaPullRequest

// int32 user_id = 1;
inline void GachaPullRequest::clear_user_id() {
  _impl_.user_id_ = 0;
}
inline int32_t GachaPullRequest::_internal_user_id() const {
  return _impl_.user_id_;
}
inline int32_t GachaPullRequest::user_id() const {
  // @@protoc_insertion_point(field_get:osr.GachaPullRequest.user_id)
  return _internal_user_id();
}
inline void GachaPullRequest::_internal_set_user_id(int32_t value) {
  
  _impl_.user_id_ = value;
}
inline void GachaPullRequest::set_user_id(int32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:osr.GachaPullRequest.user_id)
}

// int32 pull_count = 2;
inline void GachaPullRequest::clear_pull_count() {
  _impl_.pull_count_ = 0;
}
inline int32_t GachaPullRequest::_internal_pull_count() const {
  return _impl_.pull_count_;
}
inline int32_t GachaPullRequest::pull_count() const {
  // @@protoc_insertion_point(field_get:osr.GachaPullRequest.pull_count)
  return _internal_pull_count();
}
inline void GachaPullRequest::_internal_set_pull_count(int32_t value) {
  
  _impl_.pull_count_ = value;
}
inline void GachaPullRequest::set_pull_count(int32_t value) {
  _internal_set_pull_count(value);
  // @@protoc_insertion_point(field_set:osr.GachaPullRequest.pull_count)
}

// -------------------------------------------------------------------

// GameActionRequest

// int32 user_id = 1;
inline void GameActionRequest::clear_user_id() {
  _impl_.user_id_ = 0;
}
inline int32_t GameActionRequest::_internal_user_id() const {
  return _impl_.user_id_;
}
inline int32_t GameActionRequest::user_id() const {
  // @@protoc_insertion_point(field_get:osr.GameActionRequest.user_id)
  return _internal_user_id();
}
inline void GameActionRequest::_internal_set_user_id(int32_t value) {
  
  _impl_.user_id_ = value;
}
inline void GameActionRequest::set_user_id(int32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:osr.GameActionRequest.user_id)
}

// int32 choice = 2;
inline void GameActionRequest::clear_choice() {
  _impl_.choice_ = 0;
}
inline int32_t GameActionRequest::_internal_choice() const {
  return _impl_.choice_;
}
inline int32_t GameActionRequest::choice() const {
  // @@protoc_insertion_point(field_get:osr.GameActionRequest.choice)
  return _internal_choice();
}
inline void GameActionRequest::_internal_set_choice(int32_t value) {
  
  _impl_.choice_ = value;
}
inline void GameActionRequest::set_choice(int32_t value) {
  _internal_set_choice(value);
  // @@protoc_insertion_point(field_set:osr.GameActionRequest.choice)
}

// int32 scenario_id = 3;
inline void GameActionRequest::clear_scenario_id() {
  _impl_.scenario_id_ = 0;
}
inline int32_t GameActionRequest::_internal_scenario_id() const {
  return _impl_.scenario_id_;
}
inline int32_t GameActionRequest::scenario_id() const {
  // @@protoc_insertion_point(field_get:osr.GameActionRequest.scenario_id)
  return _internal_scenario_id();
}
inline void GameActionRequest::_internal_set_scenario_id(int32_t value) {
  
  _impl_.scenario_id_ = value;
}
inline void GameActionRequest::set_scenario_id(int32_t value) {
  _internal_set_scenario_id(value);
  // @@protoc_insertion_point(field_set:osr.GameActionRequest.scenario_id)
}

// -------------------------------------------------------------------

// ClientMessage

// .osr.MessageType type = 1;
inline void ClientMessage::clear_type() {
  _impl_.type_ = 0;
}
inline ::osr::MessageType ClientMessage::_internal_type() const {
  return static_cast< ::osr::MessageType >(_impl_.type_);
}
inline ::osr::MessageType ClientMessage::type() const {
  // @@protoc_insertion_point(field_get:osr.ClientMessage.type)
  return _internal_type();
}
inline void ClientMessage::_internal_set_type(::osr::MessageType value) {
  
  _impl_.type_ = value;
}
inline void ClientMessage::set_type(::osr::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:osr.ClientMessage.type)
}

// .osr.LoginRequest login = 2;
inline bool ClientMessage::_internal_has_login() const {
  return payload_case() == kLogin;
}
inline bool ClientMessage::has_login() const {
  return _internal_has_login();
}
inline void ClientMessage::set_has_login() {
  _impl_._oneof_case_[0] = kLogin;
}
inline void ClientMessage::clear_login() {
  if (_internal_has_login()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.login_;
    }
    clear_has_payload();
  }
}
inline ::osr::LoginRequest* ClientMessage::release_login() {
  // @@protoc_insertion_point(field_release:osr.ClientMessage.login)
  if (_internal_has_login()) {
    clear_has_payload();
    ::osr::LoginRequest* temp = _impl_.payload_.login_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::osr::LoginRequest& ClientMessage::_internal_login() const {
  return _internal_has_login()
      ? *_impl_.payload_.login_
      : reinterpret_cast< ::osr::LoginRequest&>(::osr::_LoginRequest_default_instance_);
}
inline const ::osr::LoginRequest& ClientMessage::login() const {
  // @@protoc_insertion_point(field_get:osr.ClientMessage.login)
  return _internal_login();
}
inline ::osr::LoginRequest* ClientMessage::unsafe_arena_release_login() {
  // @@protoc_insertion_point(field_unsafe_arena_release:osr.ClientMessage.login)
  if (_internal_has_login()) {
    clear_has_payload();
    ::osr::LoginRequest* temp = _impl_.payload_.login_;
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_login(::osr::LoginRequest* login) {
  clear_payload();
  if (login) {
    set_has_login();
    _impl_.payload_.login_ = login;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:osr.ClientMessage.login)
}
inline ::osr::LoginRequest* ClientMessage::_internal_mutable_login() {
  if (!_internal_has_login()) {
    clear_payload();
    set_has_login();
    _impl_.payload_.login_ = CreateMaybeMessage< ::osr::LoginRequest >(GetArenaForAllocation());
  }
  return _impl_.payload_.login_;
}
inline ::osr::LoginRequest* ClientMessage::mutable_login() {
  ::osr::LoginRequest* _msg = _internal_mutable_login();
  // @@protoc_insertion_point(field_mutable:osr.ClientMessage.login)
  return _msg;
}

// .osr.GachaPullRequest gacha_pull = 3;
inline bool ClientMessage::_internal_has_gacha_pull() const {
  return payload_case() == kGachaPull;
}
inline bool ClientMessage::has_gacha_pull() const {
  return _internal_has_gacha_pull();
}
inline void ClientMessage::set_has_gacha_pull() {
  _impl_._oneof_case_[0] = kGachaPull;
}
inline void ClientMessage::clear_gacha_pull() {
  if (_internal_has_gacha_pull()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.gacha_pull_;
    }
    clear_has_payload();
  }
}
inline ::osr::GachaPullRequest* ClientMessage::release_gacha_pull() {
  // @@protoc_insertion_point(field_release:osr.ClientMessage.gacha_pull)
  if (_internal_has_gacha_pull()) {
    clear_has_payload();
    ::osr::GachaPullRequest* temp = _impl_.payload_.gacha_pull_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.gacha_pull_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::osr::GachaPullRequest& ClientMessage::_internal_gacha_pull() const {
  return _internal_has_gacha_pull()
      ? *_impl_.payload_.gacha_pull_
      : reinterpret_cast< ::osr::GachaPullRequest&>(::osr::_GachaPullRequest_default_instance_);
}
inline const ::osr::GachaPullRequest& ClientMessage::gacha_pull() const {
  // @@protoc_insertion_point(field_get:osr.ClientMessage.gacha_pull)
  return _internal_gacha_pull();
}
inline ::osr::GachaPullRequest* ClientMessage::unsafe_arena_release_gacha_pull() {
  // @@protoc_insertion_point(field_unsafe_arena_release:osr.ClientMessage.gacha_pull)
  if (_internal_has_gacha_pull()) {
    clear_has_payload();
    ::osr::GachaPullRequest* temp = _impl_.payload_.gacha_pull_;
    _impl_.payload_.gacha_pull_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_gacha_pull(::osr::GachaPullRequest* gacha_pull) {
  clear_payload();
  if (gacha_pull) {
    set_has_gacha_pull();
    _impl_.payload_.gacha_pull_ = gacha_pull;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:osr.ClientMessage.gacha_pull)
}
inline ::osr::GachaPullRequest* ClientMessage::_internal_mutable_gacha_pull() {
  if (!_internal_has_gacha_pull()) {
    clear_payload();
    set_has_gacha_pull();
    _impl_.payload_.gacha_pull_ = CreateMaybeMessage< ::osr::GachaPullRequest >(GetArenaForAllocation());
  }
  return _impl_.payload_.gacha_pull_;
}
inline ::osr::GachaPullRequest* ClientMessage::mutable_gacha_pull() {
  ::osr::GachaPullRequest* _msg = _internal_mutable_gacha_pull();
  // @@protoc_insertion_point(field_mutable:osr.ClientMessage.gacha_pull)
  return _msg;
}

// .osr.GameActionRequest game_action = 4;
inline bool ClientMessage::_internal_has_game_action() const {
  return payload_case() == kGameAction;
}
inline bool ClientMessage::has_game_action() const {
  return _internal_has_game_action();
}
inline void ClientMessage::set_has_game_action() {
  _impl_._oneof_case_[0] = kGameAction;
}
inline void ClientMessage::clear_game_action() {
  if (_internal_has_game_action()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.game_action_;
    }
    clear_has_payload();
  }
}
inline ::osr::GameActionRequest* ClientMessage::release_game_action() {
  // @@protoc_insertion_point(field_release:osr.ClientMessage.game_action)
  if (_internal_has_game_action()) {
    clear_has_payload();
    ::osr::GameActionRequest* temp = _impl_.payload_.game_action_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.game_action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::osr::GameActionRequest& ClientMessage::_internal_game_action() const {
  return _internal_has_game_action()
      ? *_impl_.payload_.game_action_
      : reinterpret_cast< ::osr::GameActionRequest&>(::osr::_GameActionRequest_default_instance_);
}
inline const ::osr::GameActionRequest& ClientMessage::game_action() const {
  // @@protoc_insertion_point(field_get:osr.ClientMessage.game_action)
  return _internal_game_action();
}
inline ::osr::GameActionRequest* ClientMessage::unsafe_arena_release_game_action() {
  // @@protoc_insertion_point(field_unsafe_arena_release:osr.ClientMessage.game_action)
  if (_internal_has_game_action()) {
    clear_has_payload();
    ::osr::GameActionRequest* temp = _impl_.payload_.game_action_;
    _impl_.payload_.game_action_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_game_action(::osr::GameActionRequest* game_action) {
  clear_payload();
  if (game_action) {
    set_has_game_action();
    _impl_.payload_.game_action_ = game_action;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:osr.ClientMessage.game_action)
}
inline ::osr::GameActionRequest* ClientMessage::_internal_mutable_game_action() {
  if (!_internal_has_game_action()) {
    clear_payload();
    set_has_game_action();
    _impl_.payload_.game_action_ = CreateMaybeMessage< ::osr::GameActionRequest >(GetArenaForAllocation());
  }
  return _impl_.payload_.game_action_;
}
inline ::osr::GameActionRequest* ClientMessage::mutable_game_action() {
  ::osr::GameActionRequest* _msg = _internal_mutable_game_action();
  // @@protoc_insertion_point(field_mutable:osr.ClientMessage.game_action)
  return _msg;
}

inline bool ClientMessage::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void ClientMessage::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline ClientMessage::PayloadCase ClientMessage::payload_case() const {
  return ClientMessage::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ServerResponse

// bool success = 1;
inline void ServerResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool ServerResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool ServerResponse::success() const {
  // @@protoc_insertion_point(field_get:osr.ServerResponse.success)
  return _internal_success();
}
inline void ServerResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void ServerResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:osr.ServerResponse.success)
}

// string message = 2;
inline void ServerResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ServerResponse::message() const {
  // @@protoc_insertion_point(field_get:osr.ServerResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:osr.ServerResponse.message)
}
inline std::string* ServerResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:osr.ServerResponse.message)
  return _s;
}
inline const std::string& ServerResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void ServerResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerResponse::release_message() {
  // @@protoc_insertion_point(field_release:osr.ServerResponse.message)
  return _impl_.message_.Release();
}
inline void ServerResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:osr.ServerResponse.message)
}

// int32 user_id = 3;
inline void ServerResponse::clear_user_id() {
  _impl_.user_id_ = 0;
}
inline int32_t ServerResponse::_internal_user_id() const {
  return _impl_.user_id_;
}
inline int32_t ServerResponse::user_id() const {
  // @@protoc_insertion_point(field_get:osr.ServerResponse.user_id)
  return _internal_user_id();
}
inline void ServerResponse::_internal_set_user_id(int32_t value) {
  
  _impl_.user_id_ = value;
}
inline void ServerResponse::set_user_id(int32_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:osr.ServerResponse.user_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace osr

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::osr::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::osr::MessageType>() {
  return ::osr::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_2eproto
